kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
  - main
  event:
  - push
  - custom

steps:
- name: build-api
  image: plugins/kaniko
  environment:
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    insecure: true
    repo: ${DOCKER_REGISTRY}/library/autolab-api
    dockerfile: Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    
    # --- Add these lines ---
    cache: true
    cache_repo: ${DOCKER_REGISTRY}/autolab-cache # Or any repo you want

- name: build-pdfgen
  image: plugins/kaniko
  environment:
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    insecure: true
    repo: ${DOCKER_REGISTRY}/library/autolab-pdfgen
    dockerfile: pdf_backend/Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

    cache: true
    cache_repo: ${DOCKER_REGISTRY}/library/autolab-cache