kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
- name: build-api
  image: plugins/kaniko
  settings:
    repo:
      from_secret: api_image
    dockerfile: Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: registry
    cache: true
    cache_repo:
      from_secret: cache_image
  detach: true

- name: build-pdfgen
  image: plugins/kaniko
  settings:
    repo:
      from_secret: pdfgen_image
    dockerfile: Dockerfile
    context: pdf_backend
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: registry
    cache: true
    cache_repo:
      from_secret: cache_image
  detach: true

depends_on: []

---
kind: pipeline
type: kubernetes
name: deploy

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
- name: deploy
  image: alpine/helm:latest
  environment:
    KUBECONFIG: /root/.kube/config
  commands:
    - mkdir -p /root/.kube
    - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
    - helm upgrade --install autolab ./autolab-chart/autolab-chart/autolab --namespace=autolab --create-namespace --set api.image.tag=${DRONE_COMMIT_SHA:0:7} --set pdfgen.image.tag=${DRONE_COMMIT_SHA:0:7} --wait
  secrets:
    - source: kubeconfig
      target: KUBECONFIG_CONTENT

depends_on:
- build
