kind: pipeline
type: docker
name: build

trigger:
  branch:
  - main
  event:
  - push
  - custom

steps:
- name: build-api
  image: plugins/docker
  environment:
    # Inject the registry from the secret
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    insecure: true # Keep if your registry is 'localhost:5000'
    repo: ${DOCKER_REGISTRY}/autolab-api
    dockerfile: autolab-api.Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: build-pdfgen
  image: plugins/docker
  environment:
    # Inject the registry from the secret
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    insecure: true # Keep if your registry is 'localhost:5000'
    repo: ${DOCKER_REGISTRY}/autolab-pdfgen
    dockerfile: autolab-pdfgen.Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: docker
name: deploy

trigger:
  branch:
  - main
  event:
  - push
  - custom

# This 'depends_on' makes this entire pipeline (stage)
# wait for the 'build' pipeline to finish.
depends_on:
- build

steps:
- name: deploy-chart
  image: plugins/helm3
  environment:
    # Inject the registry here as well
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    kubernetes_config:
      from_secret: kubeconfig
    mode: upgrade
    install: true
    chart: autolab-chart/autolab-chart/autolab
    release: autolab
    namespace: autolab
    wait: true
    atomic: true
    set:
      - "image.repository=${DOCKER_REGISTRY}/autolab-api"
      - "image.tag=${DRONE_COMMIT_SHA:0:7}"
      - "pdfgen.image.repository=${DOCKER_REGISTRY}/autolab-pdfgen"
      - "pdfgen.image.tag=${DRONE_COMMIT_SHA:0:7}"