kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
  - main
  event:
  - push
  - custom

steps:
- name: build-api
  image: plugins/kaniko
  settings:
    insecure: true
    repo: 
      from_secret: api_image
    dockerfile: Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    
    cache: true
    cache_repo:
      from_secret: cache_image

- name: build-pdfgen
  image: plugins/kaniko
  settings:
    insecure: true
    repo: 
      from_secret: pdfgen_image
    dockerfile: pdf_backend/Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

    cache: true
    cache_repo:
      from_secret: cache_image