kind: pipeline
type: kubernetes
name: build-and-deploy-autolab

trigger:
  branch:
  - main
  event:
  - push

services:
- name: docker-dind
  image: docker:20.10.17-dind
  privileged: true

steps:
- name: build-api
  image: plugins/docker
  environment:
    DOCKER_HOST: tcp://docker-dind:2375
    # Inject the registry from the new secret
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    # 'insecure: true' is needed if your registry doesn't use valid HTTPS
    # (like localhost:5000). Remove if your $REGISTRY is e.g., Docker Hub.
    insecure: true
    # Use the variable to construct the repo name
    repo: ${DOCKER_REGISTRY}/autolab-api
    dockerfile: autolab-api.Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: build-pdfgen
  image: plugins/docker
  environment:
    DOCKER_HOST: tcp://docker-dind:2375
    # Inject the registry from the new secret
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    insecure: true
    # Use the variable to construct the repo name
    repo: ${DOCKER_REGISTRY}/autolab-pdfgen
    dockerfile: autolab-pdfgen.Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy-chart
  image: plugins/helm3
  # Inject the registry here as well for the 'set' command
  environment:
    DOCKER_REGISTRY:
      from_secret: docker_registry
  settings:
    kubernetes_config:
      from_secret: kubeconfig
    mode: upgrade
    install: true
    chart: autolab-chart/autolab-chart/autolab
    release: autolab
    namespace: autolab
    wait: true
    atomic: true
    set:
      # We now set the full repository path and the tag
      - "image.repository=${DOCKER_REGISTRY}/autolab-api"
      - "image.tag=${DRONE_COMMIT_SHA:0:7}"
      - "pdfgen.image.repository=${DOCKER_REGISTRY}/autolab-pdfgen"
      - "pdfgen.image.tag=${DRONE_COMMIT_SHA:0:7}"
  depends_on:
  - build-api
  - build-pdfgen