kind: pipeline
type: kubernetes
name: build-api

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
- name: build-api
  image: plugins/kaniko
  settings:
    repo:
      from_secret: api_image
    dockerfile: Dockerfile
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: registry
    cache: true
    cache_repo:
      from_secret: cache_image

---
kind: pipeline
type: kubernetes
name: build-pdfgen

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
- name: build-pdfgen
  image: plugins/kaniko
  settings:
    repo:
      from_secret: pdfgen_image
    dockerfile: pdf_backend/Dockerfile
    context: pdf_backend
    tags: "${DRONE_COMMIT_SHA:0:7}"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry:
      from_secret: registry
    cache: true
    cache_repo:
      from_secret: cache_image

---
kind: pipeline
type: kubernetes
name: deploy

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
- name: deploy
  image: alpine/helm:latest
  environment:
    API_IMAGE:
      from_secret: api_image
    PDFGEN_IMAGE:
      from_secret: pdfgen_image
  commands:
    - echo "Using API_IMAGE=$API_IMAGE and PDFGEN_IMAGE=$PDFGEN_IMAGE"
    - helm upgrade --install autolab ./autolab-chart/autolab-chart/autolab \
        --namespace=autolab --create-namespace \
        --set image.repository=$API_IMAGE \
        --set pdfgen.image.repository=$PDFGEN_IMAGE \
        --set image.tag=${DRONE_COMMIT_SHA:0:7} \
        --set pdfgen.image.tag=${DRONE_COMMIT_SHA:0:7} \
        --wait

depends_on:
- build-api
- build-pdfgen