version: "3"

vars:
  # Docker Hub images
  HUB_API_IMAGE: "grekodocker/autolab-api"
  HUB_PDF_IMAGE: "grekodocker/autolab-pdf"
  TAG: '{{.TAG | default "latest"}}'
  # Helm/Kubernetes
  NAMESPACE: '{{.NAMESPACE | default "autolab"}}'
  RELEASE_NAME: '{{.RELEASE_NAME | default "autolab"}}'
  CHART_PATH: "./autolab-chart/autolab-chart/autolab"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Docker build tasks
  build:
    desc: Build all Docker images
    deps:
      - build-backend
      - build-pdfgen

  build-backend:
    desc: Build backend Docker image
    cmds:
      - docker build . -t {{.HUB_API_IMAGE}}:{{.TAG}}

  build-pdfgen:
    desc: Build PDF generator Docker image
    dir: pdf_backend
    cmds:
      - docker build . -t {{.HUB_PDF_IMAGE}}:{{.TAG}}

  push:
    desc: Push all Docker images to Docker Hub
    cmds:
      - docker push {{.HUB_API_IMAGE}}:{{.TAG}}
      - docker push {{.HUB_PDF_IMAGE}}:{{.TAG}}

  release:
    desc: Build and push all Docker images to Docker Hub
    cmds:
      - task: build
      - task: push

  # Helm deployment tasks
  deploy:
    desc: Deploy/upgrade using Helm
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.CHART_PATH}} --namespace {{.NAMESPACE}} --create-namespace --set image.tag={{.TAG}} --set pdfgen.image.tag={{.TAG}}

  deploy-dry-run:
    desc: Preview Helm deployment (dry-run)
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.CHART_PATH}} --namespace {{.NAMESPACE}} --create-namespace --set image.tag={{.TAG}} --set pdfgen.image.tag={{.TAG}} --dry-run

  undeploy:
    desc: Uninstall Helm release
    cmds:
      - helm uninstall {{.RELEASE_NAME}} --namespace {{.NAMESPACE}}

  redeploy:
    desc: Build, push, and deploy
    cmds:
      - task: release
      - task: deploy

  restart:
    desc: Restart pods (pull latest images)
    cmds:
      - kubectl rollout restart statefulset/{{.RELEASE_NAME}}-autolab-api -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/autolab-pdfgen -n {{.NAMESPACE}}

  status:
    desc: Show deployment status
    cmds:
      - helm status {{.RELEASE_NAME}} --namespace {{.NAMESPACE}}
      - kubectl get pods -n {{.NAMESPACE}} -l app.kubernetes.io/instance={{.RELEASE_NAME}}

  logs:
    desc: Show logs from API pod
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app=autolab-api --tail=100 -f

  logs-pdf:
    desc: Show logs from PDF generator pod
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app=autolab-pdfgen --tail=100 -f

  # Development tasks
  dev:
    desc: Start frontend and backend in development mode
    deps:
      - task: frontend-deps
        silent: true
    cmds:
      - task: dev-parallel

  frontend-deps:
    desc: Install frontend dependencies if needed
    dir: carpaintr-front
    status:
      - test -d node_modules
    cmds:
      - npm install

  dev-parallel:
    desc: Run frontend and backend in parallel
    deps:
      - task: frontend
      - task: backend

  frontend:
    desc: Start frontend development server
    dir: carpaintr-front
    cmds:
      - npm run dev

  backend:
    desc: Start backend with hot reload
    dir: backend-service-rust
    cmds:
      - cargo watch -x run
