version: "3"

vars:
  # Docker Hub images
  HUB_API_IMAGE: "grekodocker/autolab-api"
  HUB_PDF_IMAGE: "grekodocker/autolab-pdf"
  TAG:
    sh: git rev-parse --short HEAD
  # Helm/Kubernetes
  CHART_PATH: "./autolab-chart/autolab-chart/autolab"
  # Environment configs (dev is default)
  ENV: '{{.ENV | default "dev"}}'
  # Environment-specific settings
  NAMESPACE_dev: "autolab-dev"
  NAMESPACE_staging: "autolab-staging"
  NAMESPACE_prod: "autolab-prod0"
  RELEASE_dev: "autolab-dev"
  RELEASE_staging: "autolab-staging"
  RELEASE_prod: "autolab-prod"
  VALUES_dev: "values-dev.yaml"
  VALUES_staging: "values-staging.yaml"
  VALUES_prod: "values-prod.yaml"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Docker build tasks
  build:
    desc: Build all Docker images
    deps:
      - build-backend
      - build-pdfgen

  build-backend:
    desc: Build backend Docker image
    cmds:
      - docker build . -t {{.HUB_API_IMAGE}}:{{.TAG}}

  build-pdfgen:
    desc: Build PDF generator Docker image
    dir: pdf_backend
    cmds:
      - docker build . -t {{.HUB_PDF_IMAGE}}:{{.TAG}}

  push:
    desc: Push all Docker images to Docker Hub
    cmds:
      - docker push {{.HUB_API_IMAGE}}:{{.TAG}}
      - docker push {{.HUB_PDF_IMAGE}}:{{.TAG}}

  release:
    desc: Build and push all Docker images to Docker Hub
    cmds:
      - task: build
      - task: push

  # Multi-architecture build tasks
  multiarch-setup:
    desc: Setup QEMU and buildx builder for multi-architecture builds
    cmds:
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - docker buildx create --name multiarch-builder --driver docker-container --bootstrap --use 2>/dev/null || docker buildx use multiarch-builder

  multiarch-build-backend:
    desc: Build multi-arch backend image (arm64 + amd64) sequentially
    cmds:
      - echo "Building arm64 backend..."
      - docker buildx build --builder multiarch-builder --platform linux/arm64 -t {{.HUB_API_IMAGE}}:{{.TAG}}-arm64 --push .
      - echo "Building amd64 backend..."
      - docker buildx build --builder multiarch-builder --platform linux/amd64 -t {{.HUB_API_IMAGE}}:{{.TAG}}-amd64 --push .
      - echo "Creating multi-arch manifest..."
      - docker buildx imagetools create -t {{.HUB_API_IMAGE}}:{{.TAG}} -t {{.HUB_API_IMAGE}}:latest {{.HUB_API_IMAGE}}:{{.TAG}}-arm64 {{.HUB_API_IMAGE}}:{{.TAG}}-amd64

  multiarch-build-pdfgen:
    desc: Build multi-arch PDF generator image (arm64 + amd64) sequentially
    dir: pdf_backend
    cmds:
      - echo "Building arm64 PDF generator..."
      - docker buildx build --builder multiarch-builder --platform linux/arm64 -t {{.HUB_PDF_IMAGE}}:{{.TAG}}-arm64 --push .
      - echo "Building amd64 PDF generator..."
      - docker buildx build --builder multiarch-builder --platform linux/amd64 -t {{.HUB_PDF_IMAGE}}:{{.TAG}}-amd64 --push .
      - echo "Creating multi-arch manifest..."
      - docker buildx imagetools create -t {{.HUB_PDF_IMAGE}}:{{.TAG}} -t {{.HUB_PDF_IMAGE}}:latest {{.HUB_PDF_IMAGE}}:{{.TAG}}-arm64 {{.HUB_PDF_IMAGE}}:{{.TAG}}-amd64

  multiarch-build:
    desc: Build all multi-arch Docker images (arm64 + amd64)
    deps:
      - multiarch-build-backend
      - multiarch-build-pdfgen

  multiarch-release:
    desc: Setup QEMU, build and push multi-arch images (arm64 + amd64) to Docker Hub
    cmds:
      - task: multiarch-setup
      - task: multiarch-build

  # Helm deployment tasks - Multi-stage
  # Usage: task deploy (defaults to dev)
  # Usage: task deploy ENV=staging
  # Usage: task deploy ENV=prod
  deploy:
    desc: "Deploy to environment (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
      REL: '{{index . (printf "RELEASE_%s" .ENV)}}'
      VALS: '{{index . (printf "VALUES_%s" .ENV)}}'
    cmds:
      - helm upgrade --install {{.REL}} {{.CHART_PATH}} --namespace {{.NS}} --create-namespace -f {{.CHART_PATH}}/{{.VALS}} --set image.tag={{.TAG}} --set pdfgen.image.tag={{.TAG}}

  deploy-dry-run:
    desc: "Preview Helm deployment (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
      REL: '{{index . (printf "RELEASE_%s" .ENV)}}'
      VALS: '{{index . (printf "VALUES_%s" .ENV)}}'
    cmds:
      - helm upgrade --install {{.REL}} {{.CHART_PATH}} --namespace {{.NS}} --create-namespace -f {{.CHART_PATH}}/{{.VALS}} --set image.tag={{.TAG}} --set pdfgen.image.tag={{.TAG}} --dry-run

  # Convenience aliases for each environment
  deploy-dev:
    desc: Deploy to development (autolab-dev namespace)
    cmds:
      - task: deploy
        vars:
          ENV: dev

  deploy-staging:
    desc: Deploy to staging (autolab-staging namespace)
    cmds:
      - task: deploy
        vars:
          ENV: staging

  deploy-prod:
    desc: Deploy to production (autolab-prod0 namespace)
    cmds:
      - task: deploy
        vars:
          ENV: prod

  undeploy:
    desc: "Uninstall Helm release (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
      REL: '{{index . (printf "RELEASE_%s" .ENV)}}'
    cmds:
      - helm uninstall {{.REL}} --namespace {{.NS}}

  redeploy:
    desc: "Build, push, and deploy (ENV=dev|staging|prod, default: dev)"
    cmds:
      - task: release
      - task: deploy

  redeploy-dev:
    desc: Build, push, and deploy to dev
    cmds:
      - task: release
      - task: deploy-dev

  redeploy-staging:
    desc: Build, push, and deploy to staging
    cmds:
      - task: release
      - task: deploy-staging

  redeploy-prod:
    desc: Build, push, and deploy to production
    cmds:
      - task: release
      - task: deploy-prod

  restart:
    desc: "Restart pods (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
      REL: '{{index . (printf "RELEASE_%s" .ENV)}}'
    cmds:
      - kubectl rollout restart statefulset/{{.REL}}-autolab-api -n {{.NS}}
      - kubectl rollout restart deployment/autolab-pdfgen -n {{.NS}}

  status:
    desc: "Show deployment status (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
      REL: '{{index . (printf "RELEASE_%s" .ENV)}}'
    cmds:
      - helm status {{.REL}} --namespace {{.NS}}
      - kubectl get pods -n {{.NS}} -l app.kubernetes.io/instance={{.REL}}

  status-all:
    desc: Show deployment status for all environments
    cmds:
      - echo "=== DEV (autolab-dev) ==="
      - kubectl get pods -n autolab-dev 2>/dev/null || echo "No pods in autolab-dev"
      - echo ""
      - echo "=== STAGING (autolab-staging) ==="
      - kubectl get pods -n autolab-staging 2>/dev/null || echo "No pods in autolab-staging"
      - echo ""
      - echo "=== PROD (autolab-prod0) ==="
      - kubectl get pods -n autolab-prod0 2>/dev/null || echo "No pods in autolab-prod0"

  logs:
    desc: "Show logs from API pod (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
    cmds:
      - kubectl logs -n {{.NS}} -l app=autolab-api --tail=100 -f

  logs-pdf:
    desc: "Show logs from PDF generator pod (ENV=dev|staging|prod, default: dev)"
    vars:
      NS: '{{index . (printf "NAMESPACE_%s" .ENV)}}'
    cmds:
      - kubectl logs -n {{.NS}} -l app=autolab-pdfgen --tail=100 -f

  # Development tasks
  dev:
    desc: Start frontend and backend in development mode
    deps:
      - task: frontend-deps
        silent: true
    cmds:
      - task: dev-parallel

  frontend-deps:
    desc: Install frontend dependencies if needed
    dir: carpaintr-front
    status:
      - test -d node_modules
    cmds:
      - npm install

  dev-parallel:
    desc: Run frontend and backend in parallel
    deps:
      - task: frontend
      - task: backend

  frontend:
    desc: Start frontend development server
    dir: carpaintr-front
    cmds:
      - npm run dev

  backend:
    desc: Start backend with hot reload
    dir: backend-service-rust
    cmds:
      - cargo watch -x run
