apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autolab.fullname" . }}-pdfgen
  labels:
    {{- include "autolab.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdfgen
spec:
  replicas: {{ .Values.autolabPdfgen.replicaCount }}
  selector:
    matchLabels:
      {{- include "autolab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pdfgen
  template:
    metadata:
      labels:
        {{- include "autolab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pdfgen
    spec:
      terminationGracePeriodSeconds: {{ .Values.autolabPdfgen.terminationGracePeriodSeconds }}
      containers:
      - name: autolab-pdfgen
        image: "{{ .Values.autolabPdfgen.image.repository }}:{{ .Values.autolabPdfgen.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.autolabPdfgen.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.autolabPdfgen.service.targetPort }}
        resources:
          limits:
            cpu: "{{ .Values.autolabPdfgen.resources.limits.cpu }}"
            memory: "{{ .Values.autolabPdfgen.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.autolabPdfgen.resources.requests.cpu }}"
            memory: "{{ .Values.autolabPdfgen.resources.requests.memory }}"
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.autolabPdfgen.env.environment }}"