apiVersion: v1
kind: Service
metadata:
  name: {{ include "autolab.fullname" . }}-api
  labels:
    {{- include "autolab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.autolabApi.service.type }}
  ports:
    - port: {{ .Values.autolabApi.service.port }}
      targetPort: {{ .Values.autolabApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "autolab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api