apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autolab.fullname" . }}-api
  labels:
    {{- include "autolab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.autolabApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "autolab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "autolab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      terminationGracePeriodSeconds: {{ .Values.autolabApi.terminationGracePeriodSeconds }}
      containers:
      - name: autolab-api
        image: "{{ .Values.autolabApi.image.repository }}:{{ .Values.autolabApi.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.autolabApi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.autolabApi.service.targetPort }}
        resources:
          limits:
            cpu: "{{ .Values.autolabApi.resources.limits.cpu }}"
            memory: "{{ .Values.autolabApi.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.autolabApi.resources.requests.cpu }}"
            memory: "{{ .Values.autolabApi.resources.requests.memory }}"
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.autolabApi.env.environment }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.autolabApi.secretName }}
              key: SECRET_KEY
        - name: LICENSE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.autolabApi.secretName }}
              key: SECRET_KEY_LICENSE
        - name: DATABASE_URL
          value: "{{ .Values.autolabApi.env.databaseUrl }}"
        - name: ADMIN_FILE_PATH
          value: "{{ .Values.autolabApi.env.adminFilePath }}"
        - name: DATA_DIR_PATH
          value: "{{ .Values.autolabApi.env.dataDirPath }}"
        - name: PDF_GEN_URL_POST
          value: "http://{{ include "autolab.fullname" . }}-pdfgen/generate"
        - name: LOG_FILE_PATH
          value: "{{ .Values.autolabApi.env.logFilePath }}"
        - name: LICENSE_CACHE_SIZE
          value: "{{ .Values.autolabApi.env.licenseCacheSize }}"
        volumeMounts:
        - name: autolab-api-storage
          mountPath: /app/data
        - name: secret-volume
          mountPath: /var/secrets/
          readOnly: true
      volumes:
      - name: autolab-api-storage
        hostPath:
          path: {{ .Values.autolabApi.persistence.hostPath }}
          type: DirectoryOrCreate
      - name: secret-volume
        secret:
          secretName: {{ .Values.autolabApi.secretName }}
          items:
            - key: admins.txt
              path: admins.txt