apiVersion: v1
kind: Service
metadata:
  name: {{ include "autolab-api.fullname" . }}
  labels:
    {{- include "autolab-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "autolab-api.selectorLabels" . | nindent 4 }}