#!/usr/bin/env python3
"""
Mock PDF/HTML generation server for local development.

Listens on port 5000 (same as the real pdf_backend service).
The Rust backend calls:
  POST {PDF_GEN_URL_POST}/pdf   → expects application/pdf response
  POST {PDF_GEN_URL_POST}/html  → expects text/plain HTML response

Run standalone: python3 scripts/mock-pdf-server.py [port]
Started automatically by: task dev
"""
import json
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer

PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 5000

# Minimal but structurally valid PDF so %PDF magic bytes are present.
_MINIMAL_PDF = b"""%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>>>endobj
xref
0 4
0000000000 65535 f\x20
0000000009 00000 n\x20
0000000058 00000 n\x20
0000000115 00000 n\x20
trailer<</Size 4/Root 1 0 R>>
startxref
200
%%EOF
"""

_MOCK_HTML = b"""<!DOCTYPE html>
<html><head><title>Mock PDF Preview</title></head>
<body><h1>Mock calculation output</h1><p>Generated by mock-pdf-server</p></body>
</html>
"""


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        print(f"[mock-pdf] {self.address_string()} {fmt % args}", flush=True)

    def _read_body(self):
        length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(length) if length else b""

    def _send(self, status, content_type, body):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path in ("/health", "/"):
            self._send(200, "application/json", b'{"status":"ok","mock":true}')
        else:
            self._send(404, "text/plain", b"not found")

    def do_POST(self):
        self._read_body()  # consume body so connection stays clean
        path = self.path.rstrip("/")
        if path.endswith("/pdf"):
            self._send(200, "application/pdf", _MINIMAL_PDF)
        elif path.endswith("/html"):
            self._send(200, "text/plain", _MOCK_HTML)
        else:
            # Fallback: treat any /generate post as PDF
            self._send(200, "application/pdf", _MINIMAL_PDF)


if __name__ == "__main__":
    server = HTTPServer(("0.0.0.0", PORT), Handler)
    print(f"[mock-pdf] Listening on :{PORT}  (POST /generate/pdf → PDF, POST /generate/html → HTML)", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
